import { useState } from 'react'
import { OrderCard } from '../components/Cards'
import { useApp } from '../context/AppContext'
import { calculateDriverEarnings } from '../utils/pricingUtils'
import { formatCurrency } from '../utils/formatCurrency'
import type { OrderStatus } from '../types'
import './RolePages.css'

const merchantId = 'merchant-002'

export function MerchantDashboard({ onReturnToCustomer }: { onReturnToCustomer: () => void }) { const { activeRole, orders, updateOrderStatus } = useApp(); const merchantOrders = orders.filter((order) => order.merchantId === merchantId); const pending = merchantOrders.filter((order) => order.status === 'pending'); const revenue = merchantOrders.filter((order) => order.status === 'delivered').reduce((total, order) => total + (order.subtotal ?? order.total), 0); const action = (orderId: string, status: OrderStatus) => updateOrderStatus(orderId, status); return <div className="page-content role-page"><section className="page-heading"><p className="eyebrow">ESPACE COMMERÇANT · MODE DÉMO</p><h1>Bonjour, Le Patio 👋</h1><p>Gérez vos commandes en quelques gestes.</p></section><div className="role-switch"><strong>Compte actif : {activeRole}</strong><button onClick={onReturnToCustomer}>Revenir au client</button></div><div className="stats-grid"><div><span>Commandes aujourd’hui</span><strong>{merchantOrders.length}</strong></div><div><span>En attente</span><strong>{pending.length}</strong></div><div><span>Chiffre d’affaires</span><strong>{formatCurrency(revenue)}</strong></div></div><section className="section-block"><div className="section-heading"><div><p className="eyebrow">COMMANDES</p><h2>À traiter maintenant</h2></div></div><div className="order-list">{merchantOrders.length ? merchantOrders.map((order) => <div key={order.id} className="workflow-card"><OrderCard order={order} onOpen={() => undefined} /><div className="workflow-actions">{order.status === 'pending' ? <><button onClick={() => action(order.id, 'accepted')}>Accepter</button><button className="danger-action" onClick={() => action(order.id, 'merchant_rejected')}>Refuser</button></> : null}{order.status === 'accepted' ? <button onClick={() => action(order.id, 'preparing')}>Commencer préparation</button> : null}{order.status === 'preparing' ? <button onClick={() => action(order.id, 'ready')}>Commande prête</button> : null}</div></div>) : <div className="empty-state"><span>✓</span><strong>Aucune commande</strong><p>Les nouvelles commandes apparaîtront ici.</p></div>}</div></section></div> }

export function DriverDashboard({ onReturnToCustomer }: { onReturnToCustomer: () => void }) { const { orders, updateOrderStatus, confirmDelivery } = useApp(); const [online, setOnline] = useState(false); const [pin, setPin] = useState(''); const [pinError, setPinError] = useState(''); const available = orders.filter((order) => order.status === 'ready'); const assigned = orders.find((order) => order.status === 'driver_assigned'); const active = orders.find((order) => ['picked_up', 'delivering'].includes(order.status)); const handleConfirm = () => { if (!active || !confirmDelivery(active.id, pin)) { setPinError('Le code PIN est invalide.'); return } setPinError('') }; return <div className="page-content role-page"><section className="page-heading"><p className="eyebrow">ESPACE LIVREUR · MODE DÉMO</p><h1>Bonjour Koffi 👋</h1><p>Les étapes de votre tournée, au même endroit.</p></section><div className="role-switch"><strong>{online ? '● En ligne' : '○ Hors ligne'}</strong><button onClick={() => setOnline(!online)}>{online ? 'Passer hors ligne' : 'Se mettre en ligne'}</button><button onClick={onReturnToCustomer}>Revenir au client</button></div>{assigned ? <section className="delivery-panel"><p className="eyebrow">COURSE ASSIGNÉE</p><h2>{assigned.merchantName}</h2><p>{assigned.deliveryAddress ?? 'Quartier Commerce, Adzopé'}</p><button className="primary-button" onClick={() => updateOrderStatus(assigned.id, 'picked_up')}>Commande récupérée</button></section> : null}{active ? <section className="delivery-panel"><p className="eyebrow">LIVRAISON EN COURS</p><h2>{active.merchantName}</h2><p>{active.deliveryAddress ?? 'Quartier Commerce, Adzopé'}</p>{active.status === 'picked_up' ? <button className="primary-button" onClick={() => updateOrderStatus(active.id, 'delivering')}>Commencer livraison</button> : <><label>Code PIN client<input value={pin} onChange={(event) => { setPin(event.target.value); setPinError('') }} placeholder="4 chiffres" inputMode="numeric" /></label>{pinError ? <p className="checkout-error" role="alert">{pinError}</p> : null}<button className="primary-button" onClick={handleConfirm}>Confirmer livraison</button></>}</section> : null}<section className="section-block"><div className="section-heading"><div><p className="eyebrow">COURSES DISPONIBLES</p><h2>{online ? 'À accepter' : 'Passez en ligne pour recevoir des courses'}</h2></div></div>{online && available.length ? <div className="order-list">{available.map((order) => <div className="workflow-card" key={order.id}><OrderCard order={order} onOpen={() => undefined} /><div className="workflow-actions"><button onClick={() => updateOrderStatus(order.id, 'driver_assigned')}>Accepter · {formatCurrency(calculateDriverEarnings(order.deliveryFee ?? 0))}</button></div></div>)}</div> : <div className="empty-state"><span>⌖</span><strong>{online ? 'Aucune course disponible' : 'Vous êtes hors ligne'}</strong><p>Le statut du livreur contrôle les courses proposées.</p></div>}</section></div> }

